name: node
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Anatoly Pulyaevskiy <email@example.com>

environment:
  sdk: '>=2.0.0-dev.19.0 <2.0.0'

dependencies:
  js: ^0.6.1

dev_dependencies:
  test: ^0.12.0
